name: Release Please Documents API
on:
  push:
    branches:
      - main
    paths:
      - "packages/test-api/**"
  pull_request:
    paths:
      - "packages/test-api/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: test-api
          path: packages/test-api
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Other","hidden":false},{"type": "refactor","section": "Other"},{"type":"docs","section":"Other","hidden":false},{"type":"style","section":"Other","hidden":false},{"type":"perf","section":"Performance improvements","hidden":false},{"type":"test","section":"Tests","hidden":false}]'
